dotless-de/vagrant-vbguest

lib/vagrant-vbguest/installers/redhat.rb
The official CentOS 7 vagrant box at https://vagrantcloud.com/centos/boxes/7 does not have bzip2 installed by default. When you use the vagrant-vbguest plugin on it, it will fail with the following error message:
```
Installing Virtualbox Guest Additions 4.3.28 - guest version is 
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.28 Guest Additions for Linux............
VirtualBox Guest Additions installer
Please install the bzip2 utility.
Copying additional installer modules ...
./install.sh: line 344: bzip2: command not found
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
./install.sh: line 357: bzip2: command not found
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous …
```
=> add bzip2 to RHEL dependencies

lib/vagrant-vbguest/installers/fedora.rb
Here's a more robust version of detecting dnf or yum, which doesn't rely on `which`.
=> Fedora 22 & 23 fail: 'which' not installed

lib/vagrant-vbguest/installers/opensuse.rb
There is no kernel-devel on opensuse. Instead we use the zypper "patterns". I added some patterns, that maybe are more than the necessary. However it works as expected.
=> opensuse should install based on the patterns

lib/vagrant-vbguest/installers/linux.rb
Switch to using the rubies "Element Reference" feature to directly get the substring instead of an array based on advice from <robert.schulze@dotless.de>, results in clear to read code.
=> OPTIMIZE: based on advice from <robert.schulze@dotless.de>

lib/vagrant-vbguest/hosts/virtualbox.rb
Added support for emvironement variable VBOX_MSI_INSTALL_PATH which gets set on newer versions of Virtual Box instead of VBOX_INSTALL_PATH. This way, the plugin will find the VBoxGuestAdditions.iso which comes with the installation of never virtual box versions again.
closes #205
=> Support for new ENV Variable VBOX_MSI_INSTALL_PATH

lib/vagrant-vbguest/download.rb, locales/en.yml, vagrant-vbguest.gemspec
And some other typo mistakes
Fixed: https://github.com/dotless-de/vagrant-vbguest/issues/189
=> Fixed: File.unlink exception on Windows

lib/vagrant-vbguest/machine.rb
Commit [b679d5a](https://github.com/soveran/micromachine/commit/b679d5ae52909bc0cfae341b6a4e12f95da41555#diff-25e7e2ab2cecabe612c9d1a001bc992eL54l) in soveran/micromachine removed the overloaded == operator for state machines.  I ran into this with some vagrant boxes that required a reboot after upgrading virtual box tools.  Because == now compares the state machine object to a string, [installation_ran? in machine.rb](https://github.com/dotless-de/vagrant-vbguest/blob/v0.12.0/lib/vagrant-vbguest/machine.rb#L48) always returns false.  So instead of running the reboot state (see [machine.rb L60](https://github.com/dotless-de/vagrant-vbguest/blob/v0.12.0/lib/vagrant-vbguest/machine.rb#L60)), vbguest fails with a loop detected since it proceeds to start instead: …
=> Overloaded == was removed in micromachine 2.0.0

lib/vagrant-vbguest.rb, lib/vagrant-vbguest/installers/archlinux.rb, lib/vagrant-vbguest/installers/debian.rb, lib/vagrant-vbguest/installers/linux.rb
Add an Archlinux installer
I left out installing linux-headers as a dependency because you can't get the older headers that match the running kernel if they are not already installed (which they often are) because Arch is rolling release, so you'd have to do a full system upgrade which would require another reboot before compiling the VirtualBox Guest Additions kernel modules. Also because the latest 4.6.4-1 kernel-headers don't seem to work with vbguest 5.0.8 (the one I tested with) I think it's better to just assume that kernel-headers are installed.
```
/var/lib/dkms/vboxguest/5.0.8/build/vboxguest/r0drv/linux/memobj-r0drv-linux.c:1032:14: error: too many arguments to function ‘get_user_pages’
rc = get_user_pages(pTask,                  /* Task for fault accounting. */
^~~~~~~~~~~~~~ …
```
=> add archlinux installer

lib/vagrant-vbguest/vagrant_compat/vagrant_1_1/command.rb
* Adds code necessary to display synopsis for `vagrant --help` and `vagrant list-commands`.
* #235 
* Ran `bundle exec vagrant`.
* Manual test of local plugin installation.
=> Add synopsis for help/list-commands (fixes #235)

lib/vagrant-vbguest/installers/debian.rb
Update debian.rb to check if it is a pve based kernel (by testing `uname -r | grep pve`), than change kernel headers package prefix to be `pve-headers` instead of `linux-headers` so this plugin could grab the correct package to install vbguest (fixes #196)
=> add support for proxmox VE

lib/vagrant-vbguest/installers/base.rb, lib/vagrant-vbguest/installers/linux.rb
- Replaces all occurrences of `yield_installation_waring` with `yield_installation_warning`.
=> Fix yield_installation_waring name

lib/vagrant-vbguest/installers/debian.rb
Oh... Spent a lot of time before figured out that issue was with vbguest plugin
We should always be aware of the errors of ```apt-get update``` and continue to work even if it is failing
=> Update debian.rb. Fix apt-get update

lib/vagrant-vbguest/installers/debian.rb
Fixes #255 (Debian Installer throws "undefined method `merge' for nil:NilClass").
The issue appears to have been introduced by 1ec80596afdaefad15f399a1eb29d000055e3e13, so it probably affected both v0.14.0 and v0.14.1. This handling logic already exists [over in `ubuntu.rb`](https://github.com/dotless-de/vagrant-vbguest/blob/daf3cf8cc1604740277925f34d1398e6d0c386a3/lib/vagrant-vbguest/installers/ubuntu.rb#L29), I'm just applying it to the Debian installer here.
=> Support a no-options install in the Debian Installer (fixes #255)

lib/vagrant-vbguest/installers/linux.rb, locales/en.yml
- Adds code necessary to display the mount point used, which adds more reporting of progress and debugging information for the user.
- Adds functionality which will be useful to have for vagrant-vbguest extension plugins to utilize, for OSes where the mount point might be less predictable than in OSes currently supported by vbguest.
- None
- Manual test of local plugin installation.
- Ran `vagrant up` and verified new functionality against an Ubuntu image.
=> Add logging of mount location

lib/vagrant-vbguest/installers/linux.rb
After noticing that https://github.com/dotless-de/vagrant-vbguest/commit/e8006b285978c8a64d12eb2e5ac14b915c51115f introduced the `yes` configuration option (eg the yes-to-everything setting which defaults to `true`), I continued to experience #252, where installation was still being cancelled. 
Looking into this further, I noticed that the `yes` function on the installer class was looking up the `@yes` instance variable (`nil` as it doesn't exist) rather than `@options[:yes]` where the option actually is.
This PR looks up the right spot and fixes a minor typo in the comment.
=> Fix `yes` option behaviour so that it works

lib/vagrant-vbguest/installers/redhat.rb
This patch adds the kernel-devel package to the list of dependencies.
This keeps previous behavior of installing kernel-devel-`uname -r` while
also installing kernel-devel. If a package is not found, yum will
continue to install the packages it does find, so there is no issue with
essentially listing it twice.
=> (GH-298) Fix bug on EL7 where shared folders would not work

locales/en.yml
The `vagrant_vbguest.status.clean` message, "No installation found", is ambiguous and it doesn't give enough context.
```
...
==> main-machine: Waiting for machine to boot. This may take a few minutes...
main-machine: SSH address: 127.0.0.1:2200
main-machine: SSH username: vagrant
main-machine: SSH auth method: private key
main-machine: 
main-machine: Vagrant insecure key detected. Vagrant will automatically replace
main-machine: this with a newly generated keypair for better security.
main-machine: 
main-machine: Inserting generated public key within guest...
main-machine: Removing insecure key from the guest if it's present...
main-machine: Key inserted! Disconnecting and reconnecting using new SSH key...
==> main-machine: Machine booted and ready!
[main-machine] No installation found. …
```
=> Update the clean status message.

lib/vagrant-vbguest/installers/centos.rb
caches the “yum info” result, so we don’t need to run it twice.
[ref #317]
=> CentOS keeps default redhat dependencies if kernel-devel-`uname -r` exists

lib/vagrant-vbguest/installers/centos.rb
I was able to test this on a CentOS 6 and a CentOS 7 box successfully but only with Vagrant 2.2.3.
=> centos 6 doesn't have three components in its version number

lib/vagrant-vbguest/installers/linux.rb
Fixes for the breakage that happened with version 6.0.6, as discussed in https://github.com/dotless-de/vagrant-vbguest/issues/333.
=> Fix for virtualbox 6.0.6

vagrant-vbguest.gemspec
micromachine is at 3.0.0 for quite some time...
>  3.0.0 - August 20, 2017 (9.5 KB) 
[https://rubygems.org/gems/micromachine](https://rubygems.org/gems/micromachine)
=> dependency on micromachine changed to 3.0

Readme.md, lib/vagrant-vbguest/hosts/virtualbox.rb
Although this might seem trivial, the VirtualBox download server doesn't redirect HTTP traffic to HTTPS.
To test this one could run:
```
curl -I http://download.virtualbox.org/virtualbox
```
Where the server responds with a `200` code instead of a `301` like it should. To mitigate this, we should just reference the `https://` endpoint like so.
=> Set web_path endpoint to utilise HTTPS

lib/vagrant-vbguest/installers/centos.rb, lib/vagrant-vbguest/installers/redhat.rb
See issue #359 and PR #338. 
Regression tested with RHEL 7, and CentOS 6 and 7.
=> Fix RHEL and CentOS installers for version 8

lib/vagrant-vbguest/installers/oracle.rb
Add the 'elfutils-libelf-devel' library required by Guest Additions on OL 8
Fixes #364
=> Add Missing Required OL 8 Library

lib/vagrant-vbguest/installers/debian.rb
Don't prompt for input to prevent hangs when installing dependencies.
=> debian: set DEBIAN_FRONTEND=noninteractive

lib/vagrant-vbguest/installers/linux.rb
This fixes the same issue that has been reported a number of times since #334 was merged.
#347
#376
=> Fix for not detecting GuestAdditions running in Centos 6.

lib/vagrant-vbguest/installer.rb, lib/vagrant-vbguest/installers/base.rb, lib/vagrant-vbguest/installers/linux.rb, lib/vagrant-vbguest/installers/windows.rb
… moving it out of the "install" step.
This allows "after_install" hooks to use the mounted iso.
=> Defer un-mounting the iso until cleanup

lib/vagrant-vbguest.rb
The old way, manually injecting before/after a specific vagrant middleware stopped working with vagrant v2.2.11
For me, this is not a perfect fix since it changes when vbguest runs (See hashicorp/vagrant#12046)
fixes #391
=> Use vagrants "machine_action_up" hook for our middleware

Readme.md, lib/vagrant-vbguest/installers/linux.rb
- By default, check for "vboxguest" and “vboxsf" to appear in /proc/modules
- Check using ruby for ease of matching. (No need to deal with different distro grep implementations etc)
closes #396
=> Linux kernel modules running check is now configureable

lib/vagrant-vbguest/command.rb, lib/vagrant-vbguest/installers/base.rb, lib/vagrant-vbguest/middleware.rb, vagrant-vbguest.gemspec
Fixes #409
I did a quick sweep through the codebase and fixed all `I18n` calls.
=> Splat Hash to Keyword args for I18n to be ruby 3 compatible

lib/vagrant-vbguest/installers/debian.rb
If you're trying to use the `vbguest` plugin with a custom debian-flavored box, there's a good chance you don't have `build-essential` installed. This results in the following error if you need to rebuild the kernel modules:
```
==> default: Machine booted and ready!
[default] GuestAdditions seems to be installed (6.1.22) correctly, but not running.
update-initramfs: Generating /boot/initrd.img-5.4.0-77-generic
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all …
```
=> Install build-essential in Debian installer

lib/vagrant-vbguest/installers/redhat.rb
This change checks to see if the base box platform/distro is Rocky Linux and performs the same installation as RedHat/CentOS.
=> Check for "rocky" as platform
